[package]
authors = ["Pat Goebel <putterson@gmail.com>"]
name = "jaialai"
version = "0.1.0"

[dependencies]
ggez = "0.4.0"
ncollide = "0.13.0"
nphysics2d = "0.6"
nphysics3d = "0.6"
nalgebra = "0.13.1"